### ISSUE TITLE
ERROR in ./node_modules/ngx-tippy/index.ts

### ISSUE THREAD

**Issue by gethinoakes** [tdanielcox/ngx-tippy#1]
```
ERROR in ./node_modules/ngx-tippy/index.ts
Module build failed: Error: /.../node_modules/ngx-tippy/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/.../node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by tdanielcox** [comment]
Hi, thanks for informing me about this. This library is currently not packaged, it requires webpack and typescript. I will get it packaged up this weekend though.

**Comment by gethinoakes** [comment]
Great thanks, don't know if you've heard of ng-packagr but it's a great tool that makes it much easier to package libraries for npm. 

https://github.com/dherges/ng-packagr

**Comment by mearleycf** [comment]
So in the meantime is there a fix for this?

**Comment by tdanielcox** [comment]
sorry, haven't had a chance to look at this yet. Easiest way to get around it is to just copy the directive to your own project and convert it to JS instead of TS. It's only 1 file so should be pretty easy
